name: 'Copy File Action'
description: 'An action to copy a file from a source folder to a target folder'

inputs:
  contents:
    description: 'Name of the file to copy'
    required: true
    
  source_folder:
    description: 'Source folder where the file is located'
    required: true

  target_folder:
    description: 'Target folder where the file should be copied'
    required: true
    default: 'artifact'

runs:
  using: 'composite'
  steps:
    - name: Create target directory
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}\${{ inputs.target_folder }}"

    - name: Copy file
      shell: pwsh
      run: |
        Copy-Item -Path "${{ github.workspace }}\${{ inputs.source_folder }}\${{ inputs.contents }}" `
                  -Destination "${{ github.workspace }}\${{ inputs.target_folder }}\"