name: "File Copy Workflow"
on: [push]

jobs:
  file-copy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run File Copy Action
        uses: ./.github/actions/copy-file-action
        with:
          contents: "source.txt"
          source_folder: "feed/test/main"
          target_folder: "artifact/main"
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: drop
            path: ${{ github.workspace }}/artifact
